"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { Conversation, ConversationDetail, createConversation, getConversation, listConversations, sendChatMessage } from "@/lib/ai-chat-api";

export default function ChatPage() {
  const { accessToken, isLoading, user } = useAuth(); const router = useRouter();
  const [conversations, setConversations] = useState<Conversation[]>([]); const [active, setActive] = useState<ConversationDetail | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!isLoading && !user) router.replace("/login"); }, [isLoading, router, user]);
  useEffect(() => { if (!accessToken) return; listConversations(accessToken).then(setConversations).catch((cause) => setError(cause.message)); }, [accessToken]);
  async function select(id: string) { if (!accessToken) return; setLoading(true); try { setActive(await getConversation(accessToken, id)); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load chat."); } finally { setLoading(false); } }
  async function newChat() { if (!accessToken) return; setLoading(true); try { const conversation = await createConversation(accessToken); setConversations((items) => [conversation, ...items]); await select(conversation.id); } finally { setLoading(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!accessToken || !active || !message.trim() || loading) return; const text = message.trim(); setMessage(""); setLoading(true); try { const result = await sendChatMessage(accessToken, active.id, text); await select(active.id); setActive((current) => current ? { ...current, messages: [...current.messages, { id: result.message_id, role: "assistant", content: result.message, created_at: result.created_at }] } : current); } catch (cause) { setMessage(text); setError(cause instanceof Error ? cause.message : "I couldn't analyze your data right now."); } finally { setLoading(false); } }
  if (isLoading || !user) return <main className="p-8">Loading...</main>;
  return <main className="min-h-screen bg-slate-950 p-6 text-white"><section className="mx-auto grid max-w-6xl gap-6 md:grid-cols-[240px_1fr]"><aside className="rounded border border-slate-700 p-4"><h1 className="text-xl font-bold">SalesSnap AI</h1><button className="mt-4 w-full rounded bg-cyan-400 p-2 text-slate-950" onClick={newChat}>+ New Chat</button><div className="mt-4 space-y-2">{conversations.map((item) => <button className="block w-full rounded p-2 text-left hover:bg-slate-800" key={item.id} onClick={() => select(item.id)}>{item.title}</button>)}</div></aside><section className="rounded border border-slate-700 p-5"><h2 className="text-2xl font-semibold">Chat</h2>{error && <p className="mt-3 rounded border border-rose-500 p-3">{error}</p>}<div className="my-6 space-y-4">{active?.messages.map((item) => <article className={item.role === "user" ? "ml-12 rounded bg-cyan-900 p-3" : "mr-12 rounded bg-slate-800 p-3"} key={item.id}><strong>{item.role === "user" ? "You" : "SalesSnap AI"}</strong><p>{item.content}</p></article>)}{!active && <p className="text-slate-400">Start a chat to ask about sales, stock risk, customer segments, forecasts, or anomalies.</p>}</div><form className="flex gap-2" onSubmit={submit}><input className="min-w-0 flex-1 rounded bg-slate-800 p-3" disabled={!active || loading} maxLength={4000} placeholder="Ask SalesSnap..." value={message} onChange={(event) => setMessage(event.target.value)} /><button className="rounded bg-cyan-400 px-4 text-slate-950 disabled:opacity-60" disabled={!active || loading}>{loading ? "Analyzing your SalesSnap data..." : "Send"}</button></form></section></section></main>;
}
