"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

import { useAuth } from "@/components/auth-provider";
import { Anomaly, AnomalyPage, AnomalySummary, getAnomalies, getAnomalySummary } from "@/lib/anomaly-api";

export default function AnomaliesPage() {
  const { accessToken, user, isLoading } = useAuth(); const router = useRouter();
  const [page, setPage] = useState<AnomalyPage | null>(null); const [summary, setSummary] = useState<AnomalySummary | null>(null); const [severity, setSeverity] = useState(""); const [direction, setDirection] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [selected, setSelected] = useState<Anomaly | null>(null);
  useEffect(() => { if (!isLoading && !user) router.replace("/login"); }, [isLoading, router, user]);
  const load = useCallback(() => { if (!accessToken) return; setLoading(true); const params = new URLSearchParams(); if (severity) params.set("severity", severity); if (direction) params.set("direction", direction); const query = params.size ? `?${params}` : ""; Promise.all([getAnomalies(accessToken, query), getAnomalySummary(accessToken)]).then(([nextPage, nextSummary]) => { setPage(nextPage); setSummary(nextSummary); setError(null); }).catch((requestError: Error) => setError(requestError.message)).finally(() => setLoading(false)); }, [accessToken, direction, severity]);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  if (isLoading || !user) return <main className="p-8">Loading...</main>;
  return <main className="min-h-screen bg-slate-950 p-6 text-white"><section className="mx-auto max-w-6xl space-y-6"><header><h1 className="text-3xl font-bold">Sales Anomalies</h1><p className="text-slate-400">Demand significantly different from recent historical patterns.</p></header><div className="flex gap-3"><select className="bg-slate-800 p-2" value={severity} onChange={(e) => setSeverity(e.target.value)}><option value="">All severities</option>{["low", "medium", "high", "critical"].map((item) => <option key={item}>{item}</option>)}</select><select className="bg-slate-800 p-2" value={direction} onChange={(e) => setDirection(e.target.value)}><option value="">All directions</option><option value="spike">Spike</option><option value="drop">Drop</option></select></div>{loading && <p>Loading anomalies...</p>}{error && <button className="text-rose-300 underline" onClick={load}>{error} Retry</button>}{summary && <div className="grid gap-3 sm:grid-cols-5">{[["Total", summary.total_anomalies],["Critical",summary.critical],["High",summary.high],["Spikes",summary.spikes],["Drops",summary.drops]].map(([label,value]) => <article className="rounded border border-slate-700 p-3" key={String(label)}><p>{label}</p><strong>{value}</strong></article>)}</div>}{page?.items.length === 0 && <p>No significant anomalies detected for this period. <Link className="text-cyan-300" href="/import">Import sales data</Link></p>}{page && <table className="w-full text-left text-sm"><thead><tr><th>Date</th><th>Product</th><th>Expected</th><th>Actual</th><th>Deviation</th><th>Severity</th></tr></thead><tbody>{page.items.map((item) => <tr className="cursor-pointer border-t border-slate-800" key={`${item.product.id}-${item.date}`} onClick={() => setSelected(item)}><td>{item.date}</td><td>{item.product.name}</td><td>{Number(item.expected_demand).toFixed(1)}</td><td>{item.actual_demand}</td><td>{item.deviation_percentage === null ? "N/A" : `${Number(item.deviation_percentage).toFixed(0)}%`}</td><td>{item.severity}</td></tr>)}</tbody></table>}{selected && <aside className="rounded border border-cyan-500 p-4"><h2>{selected.product.name} — {selected.date}</h2><p>{selected.direction} · {selected.confidence}</p><p>Actual {selected.actual_demand}; expected {Number(selected.expected_demand).toFixed(1)}.</p><p className="text-slate-400">Detected because demand differed significantly from the recent historical pattern; no cause is inferred.</p></aside>}</section></main>;
}
